# Background and foreground colors
background = #0D0E12
foreground = #ffffff

# Standard colors
palette = 0=#0D0E12
palette = 1=#ac827b
palette = 2=#D2D3CE
palette = 3=#E0E0D9
palette = 4=#a7a7af
palette = 5=#b4b0b5
palette = 6=#7EB4C1
palette = 7=#F2F4EE

# Bright colors
palette = 8=#787c8c
palette = 9=#d1b6b2
palette = 10=#fefefe
palette = 11=#ffffff
palette = 12=#d7d7db
palette = 13=#e1dfe2
palette = 14=#bad9e1
palette = 15=#ffffff
