background            #0D0E12
foreground            #ffffff

# black
color0  #0D0E12
color8  #787c8c

# red
color1  #ac827b
color9  #d1b6b2

# green
color2  #D2D3CE
color10 #fefefe

# yellow
color3  #E0E0D9
color11 #ffffff

# blue
color4  #a7a7af
color12 #d7d7db

# magenta
color5  #b4b0b5
color13 #e1dfe2

#cyan
color6  #7EB4C1
color14 #bad9e1

#white
color7  #F2F4EE
color15 #ffffff


